### ISSUE TITLE
Error at first launch

### ISSUE THREAD

**Issue by thibc81** [tryethernal/ethernal#109]
Hello,

after installing ethernal, I get the following error when I run ethernal on a console:

node:internal/modules/cjs/loader:1183
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: libsecret-1.so.0: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1183:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/ethernal/node_modules/keytar/lib/keytar.js:1:14)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'ERR_DLOPEN_FAILED'
}

The version of Node.js I am running is v16.13.2 and i get the following warning when I npm install ethernal -g :

npm WARN deprecated mkdirp-promise@5.0.1: This package is broken and no longer maintained. 'mkdirp' itself supports promises now, please switch to that.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated ethereumjs-tx@2.1.2: New package name format for new versions: @ethereumjs/tx. Please update.
npm WARN deprecated uuid@2.0.1: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated multicodec@1.0.4: This module has been superseded by the multiformats module
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated multibase@0.6.1: This module has been superseded by the multiformats module
npm WARN deprecated multibase@0.7.0: This module has been superseded by the multiformats module
npm WARN deprecated multicodec@0.5.7: This module has been superseded by the multiformats module
npm WARN deprecated ethereumjs-common@1.5.2: New package name format for new versions: @ethereumjs/common. Please update.
npm WARN deprecated cids@0.7.5: This module has been superseded by the multiformats module

Thank you for your help.

**Comment by antoinedc** [comment]
Hi,

This happens because there is a package missing on your environment (usually because you are running the CLI on a headless OS).

To avoid this error you can use env variables when running Ethernal commands.
For example, with Ganache:
`ETHERNAL_EMAIL=your@email.com ETHERNAL_PASSWORD=yourpwd ethernal listen`

Or with Hardhat:
`ETHERNAL_EMAIL=your@email.com ETHERNAL_PASSWORD=yourpwd npx hardhat node`

Let me know if that works

**Comment by thibc81** [comment]
Thank you for your answer. 
Unfortunately it still shows the same issue when I add the env variables to the command.
What else would libsecret load?

**Comment by antoinedc** [comment]
What version of the CLI are you using? (`ethernal --version`)
Also, can you screenshot the command & the output please?

**Comment by thibc81** [comment]
![image](https://user-images.githubusercontent.com/83956321/152774475-539439b0-7303-4610-9c9d-76fe215a1b5a.png)

**Comment by antoinedc** [comment]
Can you try running this: `npm ls ethernal --global`? This should give you the version number

**Comment by thibc81** [comment]
thanks, it returns ethernal@0.9.0

**Comment by antoinedc** [comment]
Thanks, which command did you try to run with the env variables?

**Comment by thibc81** [comment]
Any command really, for instance
>ETHERNAL_EMAIL=XXX ETHERNAL_PASSWORD=XXX  ethernal --v

**Comment by thibc81** [comment]
Solved, add to install libsecret : 
sudo apt install libsecret-1-0

**Comment by antoinedc** [comment]
Oh ok, sorry I couldn't be more helpful, I thought the env variables system would have been able to prevent from having to install this library actually...I'll work on that :)
