### ISSUE TITLE
after importing a contract, clear the address field

### ISSUE THREAD

**Issue by aspiers** [tryethernal/ethernal#131]
After importing a contract, the address field is still populated with the address of the contract which was just imported:

![image](https://user-images.githubusercontent.com/100738/158647663-ee1891fc-83c5-470f-a926-73004de1f712.png)

It's not very clear that this field is still available in order to allow you to quickly import more contracts.  Two simple tweaks would help clarify that:

- Clear the address field.
- Change the text to mention something about "Import another contract".

**Comment by antoinedc** [comment]
Done in https://github.com/tryethernal/ethernal/releases/tag/2.1.1
