### ISSUE TITLE
Pagination of block lists seems wrong

### ISSUE THREAD

**Issue by aspiers** [tryethernal/ethernal#132]
It says there are 17 blocks, but with 10 per page, only two are shown (and one is block 0 which seems like a separate bug maybe):

![image](https://user-images.githubusercontent.com/100738/158648373-40e190ab-0e0c-4211-9b10-95237b1138da.png)

**Comment by antoinedc** [comment]
Latest release should fix that, issues was that some blocks or transactions were counted multiple times in the pagination when synced multiple times.
You will need to reset the workspace to reset everything to 0 and start over though.

About block 0, I believe it comes from the node.

**Comment by aspiers** [comment]
Cool, thanks!
