### ISSUE TITLE
"Emitted Events" section repeats same request to upload artifacts

### ISSUE THREAD

**Issue by aspiers** [tryethernal/ethernal#133]
If a transaction emits events from multiple contracts, and not all of them have artifacts uploaded, I see something like this:

![image](https://user-images.githubusercontent.com/100738/158650382-40557296-4507-484d-b353-c55599995b13.png)

In this example, the first two are different events from the same contract (without artifacts uploaded), and the third (below the `StakeCreated` event) is from another contract (also without upload).

It would be better if each message mentioned 1) the contract it comes from and 2) the event topic, so that it's clearer why the message is repeated.

Furthermore, the "here" link within each of these messages links to the page for that contract address, but if that contract has no transactions, the page is empty, so it's not clear to the user how to upload artifacts.  It would be better if it linked directly to a page which allows a choice of either upload or import of artifacts for that contract address.

**Comment by antoinedc** [comment]
Done in https://github.com/tryethernal/ethernal/releases/tag/2.1.1
