### ISSUE TITLE
Contract page is missing key info

### ISSUE THREAD

**Issue by aspiers** [tryethernal/ethernal#134]
If I select a particular contract, I see something like:

![image](https://user-images.githubusercontent.com/100738/158653224-0cab89a2-621c-4246-afc8-923df54bc9f4.png)

There's some fairly crucial info missing from this view, which I would suggest should be visible at the top, before the Transactions and Contracts tabs:

- Contract address (with copy address button)
- Contract name
- Contract creator and creation transaction (if available)
- Contract balance

Something along these would be great, albeit without the adverts ;-)

![image](https://user-images.githubusercontent.com/100738/158653668-06b3f27d-e2c8-45d4-8b76-294544fc289f.png)

**Comment by antoinedc** [comment]
This is now available :)
