### ISSUE TITLE
Transactions not tracked over http

### ISSUE THREAD

**Issue by srinjoychakravarty** [tryethernal/ethernal#196]
- When I deploy hardhat contracts on a localhost hardhat instance using hardhat scripts, Ethernal can track **Transactions** _just fine_

- When I try to use Ethernal on a remote ec2 node using a hostname over **http**, the hardhat/scripts deploy.js continues to deploy the contract _just fine_ 

  ![Screenshot 2022-10-04 at 4 10 31 AM](https://user-images.githubusercontent.com/1481037/193768372-49076354-00d7-4665-a996-226faf34738c.png)

- However,  Ethernal is no longer able to track any **Transactions**, which is very disappointing 😞

  ![Screenshot 2022-10-04 at 4 10 14 AM](https://user-images.githubusercontent.com/1481037/193768692-6e2960ee-8fc4-4c4a-af95-c503ad9497f5.png)

**Comment by antoinedc** [comment]
Can you check that the hardhat.config file that is on your remote server has the correct settings? My guess is that the remote plugin (sending txs) is syncing to a different workspace/account than the local one (sending contracts data).
You should be able to see in the Hardhat logs, at the beginning, which account & which workspace it's going to connect to.
Make sure that:
- The `workspace` field is set to route53-hardhat
- The ETHERNAL_EMAIL & ETHERNAL_PASSWORD env variables contain the right credentials for this workspace

Also, feel free to ping me on Discord if it doesn't work, I'm sure we can fix this quickly, Ethernal is supposed to work quite well with remote endpoints :)

**Comment by srinjoychakravarty** [comment]
@antoinedc 
pretty sure this is a bug as I have everything setup:
the .env
```
ETHERNAL_EMAIL=*****@*****.***
ETHERNAL_PASSWORD=*********
ETHERNAL_WORKSPACE=*****
```

and the **hardhat.config.js**
```js
module.exports = {
  ethernal: {
    email: ETHERNAL_EMAIL,
    password: ETHERNAL_PASSWORD,
    workspace: ETHERNAL_WORKSPACE, 
    uploadAst: true,
  },
```

as I said, it works fine on localhost deployments...which is most peculiar 🤷🏽‍♂️

**Comment by antoinedc** [comment]
Can you check the Hardhat logs on the ec2 server? There should be some logs starting with "[Ethernal]" that print the account & workspace it's connecting to, can you post those here, please? (or send to me privately)

**Comment by srinjoychakravarty** [comment]
> Can you check the Hardhat logs on the ec2 server? There should be some logs starting with "[Ethernal]" that print the account & workspace it's connecting to, can you post those here, please? (or send to me privately)

just posted it above

**Comment by antoinedc** [comment]
I meant the logs for the ```npx hardhat node``` command
