### ISSUE TITLE
For project

### ISSUE THREAD

**Issue by CryptoDevving** [tryethernal/ethernal#199]
Am I able to use this for my cryptocurrency project? I am confused by the license.

**Comment by antoinedc** [comment]
Hi,

Yes you are. The only thing you cannot do is resell Ethernal (ie taking the code, hosting it somewhere and start selling it) or a subset of it as part of your product.

**Comment by CryptoDevving** [comment]
But I am able to use it as an explorer for my blockchain

**Comment by antoinedc** [comment]
Yes

**Comment by antoinedc** [comment]
Feel free to reopen if you have any further questions :)
