### ISSUE TITLE
How to setup firebase?

### ISSUE THREAD

**Issue by Toni-d-e-v** [tryethernal/ethernal#229]
I'm trying to self host for my cryptocurrency but I don't get it how to setup firebase with cli

![image](https://user-images.githubusercontent.com/62844491/215164521-8a849d29-1fc9-4cdf-abad-457807e74f41.png)

**Comment by Toni-d-e-v** [comment]
Error: It looks like you haven't used Cloud Firestore in this project before. Go to https://console.firebase.google.com/project/toniai/firestore to create your Cloud Firestore database.

I want this localhosted so I dont pay for firebase?

**Comment by antoinedc** [comment]
Hello! sorry this is not well documented yet, if you want this locally, the best thing would be to use docker/compose.
can you run `docker-compose up` in your directory?

**Comment by antoinedc** [comment]
Now instructions regarding how to self host are now available here: https://doc.tryethernal.com/getting-started/self-hosted#web-app-setup
I'll close this one, feel free to reopen if you have specific issues with the new version
