### ISSUE TITLE
Add support for Anvil (part of foundry) local blockchains

### ISSUE THREAD

**Issue by DegenComedian** [tryethernal/ethernal#251]
Dear developers,

I would love to have support for Anvil local blockchains like we have with hardhat.
Here is the offical link to the project: https://github.com/foundry-rs/foundry/blob/master/anvil/README.md

It basically supports all Api rpc calls: 

https://book.getfoundry.sh/reference/anvil/

**Comment by antoinedc** [comment]
Hello,

Anvil should work fine with Ethernal by default. There has even been an integration built for the CLI so it can detect local artifacts and synchronize them automatically.

Is there anything in particular that is missing? Or an additional integration that you'd like?

**Comment by DegenComedian** [comment]
no specific thing in mind, I will try to use it with Ethernal. Thanks!

**Comment by antoinedc** [comment]
I'm closing this for now, feel free to reopen/open a new issue if something doesn't work properly :)
