### ISSUE TITLE
Wrong command

### ISSUE THREAD

**Issue by nicopaulsen** [tryethernal/ethernal#290]
ssh-keyscan -H $TARGET_HOST ~/.ssh/known_hosts should be ssh-keyscan -H $TARGET_HOST >> ~/.ssh/known_hosts in the instructions

**Comment by antoinedc** [comment]
Thanks! I've fixed it

**Comment by nicopaulsen** [comment]
Hi,

Im new to ethereal and blockchain development, do you have any instructions for running a self hosted eternal instance on osx ?
